name: Umbrella

on:
  push:
     branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build solution
      run: dotnet build ./src/Umbrella.sln --configuration Debug
    - name: Run tests
      run: dotnet test ./src/Umbrella.Tests/Umbrella.Tests.csproj --no-build
      
  publish:
    runs-on: ubuntu-latest
    
    needs: build
    
    if: github.ref == 'master'
    
    steps:
      - name: Package project as NuGet package
        
